name: Publish

on:
  push:
    branches:
      - master

jobs:
  gfmtoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          TAG="docker.pkg.github.com/miyucy/rbnd/rbnd:$(date -u '+%Y%m%d%H%M%S')"
          docker build -t minid:latest -f Dockerfile.minid .
          cat Dockerfile \
            | docker run -i --rm minid:latest minid -f - \
            | docker build --build-arg APT_MIRROR=US --tag "${TAG}" -f - .
          docker login -u miyucy -p "${{ secrets.GITHUB_TOKEN }}"
          docker push "${TAG}"
